### ISSUE TITLE
能否通过这个接口找到已经在设备上删除的聊天对象

### ISSUE THREAD

**Issue by ceiminya** [hd80606b/BiliBili_Private_Msg#1]
想寻找2020年之间和一个up主私信的记录，但后来可能意外在聊天框把那个窗口清空了，已经记不清该up的ID，没法找当时的私信记录。询问客服得知，服务器上的聊天记录不会删除。那是不是能用接口，找到那个和我发过私信的up，而且必须要查询所有uid？

**Comment by hd80606b** [comment]
目前来看只能遍历uid来查了，刚刚测试了一下，消息列表的接口（/session_svr/v1/session_svr/get_sessions）只要把聊天窗口删除了，就不会返回那个up了，但是通过这个项目用到的查聊天记录的接口还是能返回与删除对象的所有聊天记录

**Comment by ceiminya** [comment]
这样是不是得放在服务器上找好久😂，我还没搞过这些，感觉挺麻烦的

**Comment by hd80606b** [comment]
对下面的接口反复发送get请求就行了
https://api.vc.bilibili.com/svr_sync/v1/svr_sync/fetch_session_msgs?sender_device_id=1&talker_id=遍历的值&session_type=1&size=20&build=0&mobi_app=web
从1到2020年大概是9位数，看返回值长度就能判断是否有消息了
（虽然脚本写起来简单，但是这数量已经接近10e了，属于是长期工程了）
